
api {
  url = "https://api.tdr-integration.nationalarchives.gov.uk/graphql"
  url = ${?API_URL}
}
auth {
  url = "https://auth.tdr-integration.nationalarchives.gov.uk"
  url = ${?AUTH_URL}
  clientId = "tdr-backend-checks"
  clientSecret = "${?CLIENT_SCRECT}"
  realm = "tdr"
}
sns {
  endpoint = "https://sns.eu-west-2.amazonaws.com"
  endpoint = ${?SNS_ENDPOINT}
  topicArn = ${?SNS_TOPIC_ARN}
}
